<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net8.0-windows</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UseWPF>true</UseWPF>
    <Platforms>AnyCPU</Platforms>
    <ApplicationIcon>Assets\AppIcon.ico</ApplicationIcon>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\GameSubRelay.Core\GameSubRelay.Core.csproj" />
    <ProjectReference Include="..\GameSubRelay.Infrastructure\GameSubRelay.Infrastructure.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.Extensions.Hosting" />
    <PackageReference Include="Microsoft.Extensions.Configuration.Binder" />
    <PackageReference Include="Microsoft.Extensions.DependencyInjection.Abstractions" />
    <PackageReference Include="WPF-UI" />
  </ItemGroup>

  <ItemGroup>
    <None Remove="Assets\AppIcon.ico" />
    <None Remove="Assets\AppIcon.png" />
    <Resource Include="Assets\AppIcon.ico" />
    <Resource Include="Assets\AppIcon.png" />
  </ItemGroup>
</Project>
